# Generated by Django 5.0.3 on 2024-06-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_user_desc_alter_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='desc',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
